// alert("Bu sitede yazdığınız metinler kadirlice'ye çevrilir.")


let kelimeler = ['aaa!', 'aabbavv', 'aaz','aal', 'acar', 'adı batasıca', 'ağzı yumulasıca', 'alabaş', 'alaf çalmak', 'alağbak', 'alemençik', 'Alim Allah', 'alkış verme', 'Allah abatlar veresi', 'amanat', 'anaç', 'anarıya gitmek', 'arısili', 'arıya gitmek', 'aşılak', 'aşma', 'aşşa', 'avara', 'avarlık', 'ayampur', 'ayaz', 'ayın esgisi', 'ayrık', 'azzık', 'bağır', 'bahta bakan', 'bambıl', 'başı esik', 'bayramcalık', 'bazlama', 'bekere', 'bıçgı', 'bıldır', 'bılız', 'bibi', 'bider', 'bidon', 'bir bonak yamır', 'birine şişmek', 'bisseel', 'bişme', 'bişşek', 'biyaktan', 'bocit', 'bor', 'boşandırmak', 'boyunduruk', 'boz', 'böö', 'böön', 'börk', 'börkenek', 'bre', 'buncaaz', 'buncalış', 'bunsukmak', 'bük', 'büvelek', 'büvet', 'caalak', 'caldırtı', 'camız', 'cangama', 'carbık', 'cardın', 'carsa', 'cascavlak', 'celfin', 'cemkirmek', 'cescevlek', 'ceyran', 'cıba', 'cıkıl', 'cılk', 'cıllıcı', 'cıllımak', 'cıngar çıkarmak', 'cırnavık', 'cırtık', 'cilkes', 'cirpinti', 'ciyeriyin sapından vurulasın', 'coruk', 'cuvara', 'cübür', 'cüllük', 'çaal', 'çandır', 'çapa', 'çardak', 'çarık', 'çarpana', 'çatalavrat', 'çatırtı', 'çaygara', 'çebiç', 'çekişmek', 'çeltik', 'çen', 'çenedini ayırmak', 'çepel', 'çeten', 'çetil', 'çevrengeç', 'çıkla', 'çıkrık', 'çıngıl', 'çınkı', 'çıtımık', 'çıtırtı', 'çili', 'çilpik', 'çimmek', 'çinçik', 'çinke', 'çisemek', 'çotul', 'çömçe', 'çul', 'çüven', 'damah', 'damızlık', 'darbız', 'davış', 'dayramak', 'demlik', 'depegolu', 'depgi', 'depik', 'deşirmek', 'devlikisüün', 'dıdısının dıdısı', 'dıkılmak', 'dıkız', 'dıngırcını avlamak', 'dıngıt', 'dışlık', 'dik', 'dil', 'dingil', 'diremince', 'dirgen', 'dokurcun', 'dombalak', 'döyüsün emzirdiği, südüğü', 'dulda', 'dutmaç', 'ebeş', 'eee! eee!', 'eerelti', 'el lehençesi', 'elefetsiz', 'eletmek', 'eli belinde', 'elleem', 'ellengeç', 'ellik', 'emilik', 'enek', 'enik', 'erinik yağ', 'esse mi?', 'eşgere', 'eşiklik', 'evlensek', 'evmek', 'evreeç', 'evsin', 'eye ekiştirmek', 'fak', 'fakı', 'fedik', 'felfellemek', 'fılcırtmak', 'fırfırı', 'fırıştak', 'fışgırık', 'filtik filtik', 'firez', 'firik', 'fiske', 'fiyd', 'gabırlık', 'gaco', 'gadasını almak', 'gadef', 'gafası firirek', 'galiç', 'gallep', 'galli', 'galp', 'gamgı', 'gamiş', 'gandak', 'gapıt', 'gara guvan', 'garaa', 'garaçalı', 'garaltı', 'garanışmak', 'garanmak', 'gareen', 'garez etmek', 'garsambaç', 'gasbalık', 'gasıl', 'gaster', 'gaşşak', 'gaşşak', 'gatık',
 'gavırga', 'gavıt', 'gavur dedengil', 'gazel', 'geliç', 'gem', 'gemini gevmek', 'gıcilo', 'gıçıırık', 'Gılik tomatis', 'gır kişmir', 'gıralaaç', 'gıran dıkıla', 'gırçarmak', 'gırıflamak', 'gırızet', 'gırklık', 'gırtgırtı', 'gısga', 'gısıkmak', 'gısır gısır torba', 'gıvratmalı', 'gıyamat gımı', 'gıyılgan', 'gıyrak', 'gıyyb gırmızı', 'gızılbacak', 'gızınmak', 'gocunmak', 'goddik', 'gompile', 'gongulu gook', 'gontak', 'goo etmek', 'gopli', 'goza çıbıı', 'göbelek', 'göcek güpre', 'göde', 'gökcek', 'gökgülü sarı', 'gön', 'göönmek', 'göööm gö', 'götün götün gitmek', 'gubarmak', 'gulunç', 'gumbilis', 'gunnacı', 'gurk tavuk', 'gurmut', 'guruyer gunduzu','guşana', 'guvan', 'guyruu tıpılatmak', 'gülle', 'gümbür', 'haçan bürülan', 'haçan', 'hakına', 'hakını avcuna koymak', 'halbır', 'halep garası', 'hambalis', 'hamzan', 'hapban gımı', 'hapban', 'haral', 'hardalatsız', 'hartlap', 'hasta yoklamak', 'haşventi', 'hayma', 'hazele', 'hebil', 'heebe', 'helik', 'helke', 'hellen hellen etmek', 'hellenmek', 'herif', 'hetif', 'hıllangaç', 'hımbıl', 'hıncırık', 'hırtık', 'hışgımı', 'hışırlı', 'hıta', 'holluğu inmek', 'holungu', 'hombuluna almak', 'hopilik', 'hopuna almak', 'horanta', 'horum', 'horuzlanmak', 'hoşarlanmak', 'hozak', 'hozu', 'hölümek', 'höpürdetmek', 'hörtük', 'hu', 'huysukmak', 'huzulu masraf', 'hümzünmek', 'hüs', 'ıralanmak', 'ırbık', 'ışgın', 'ışgıya', 'ışımadan', 'ırzıırın çocuğu', 'ısmarıç', 'ibili', 'ikirciklenmek', 'iliksiz', 'ineemen', 'it gılı postal bağı', 'garaböcük', 'kakılı', 'keçik', 'kehni', 'kekre çalmak', 'kele', 'kelekesten', 'kepmek', 'kerçine getmek', 'kertiş', 'keskenmek', 'kesme', 'keşkere', 'kilden', 'kildirmek', 'kirmen', 'kirtik', 'kirtilini çıkarmak', 'kişmir', 'kökgüç', 'kömeç', 'kör tapa', 'köre', 'köryapalak', 'köşt', 'köynek', 'kücü', 'kümül', 'küncü baalası', 'küncü', 'künde', 'kürt bülbülü', 'küşne', 'Labıt', 'laylon', 'Lemerme', 'lepe', 'Loş', 'Löküs', 'maa', 'malamat olmak', 'malamat', 'manca', 'mangılı batmak', 'massık massık yürümek', 'mavra kesmek', 'meh', 'meke patlaa', 'meke pürçüğü', 'meke sokalaa', 'meke', 'meses', 'mık', 'mıkıs', 'midesi cıkramak', 'mintan', 'mitil', 'mucuk', 'murt', 'muşamba', 'mürdün', 'müşdere olmak', 'naakıt', 'namtı', 'navıtıyon', 'ne biliim edem', 'ne tevir', 'neciimiş', 'ninemeli', 'nişe bulamacı', 'nişe', 'obalar ne der', 'ocakdan yırak', 'okuntu', 'omanı pıttırmak', 'omusilli', 'omuzla',
  'ondan kerli', 'oynum hos', 'ölgünürek lepe', 'öllün körü', 'ölümsek', 'örk', 'örme', 'örme', 'örtme', 'öteberi', 'ötürmek', 'paldın', 'palıt', 'pampal', 'parke', 'patacını ayırmak', 'pataç', 'pavkırmak', 'perpil', 'peşgir', 'pırnal', 'pırtı', 'pırtmak', 'pıslan patır', 'pısmak', 'pıtık', 'pinnik', 'pontil', 'porsumak', 'potturmak', 'pörez', 'pür', 'pürçük', 'püsü', 'saavvp sarı', 'saban', 'sacaa', 'sakadıırak', 'sakga', 'sakna', 'samı', 'santraviç', 'saplıcan', 'sarat', 'savan', 'savışmak', 'sehlik', 'seklem', 'selemet', 'sepedi seyrek', 'sepet', 'serçe oyunu', 'setirikli', 'sıklat', 'sırıtmak', 'sırtarmak', 'sırtın gılıç', 'sıykal', 'sikke', 'sili', 'sille', 'simir simir yağmak', 'simsar', 'sinmek', 'sinsin oyunu', 'sivtimek', 'soğukluk gatmacı', 'soğukluk', 'sokum', 'somak eşgisi', 'soyka', 'sömelek', 'söykenmek', 'sultanı kiraz', 'sülük', 'sündürüm', 'süngüç', 'sürek', 'süven', 'süyük', 'şapcak', 'şaplak', 'şavşırı', 'şek şek gonuşmak', 'şelek', 'şıfan', 'şif', 'şinik', 'şire', 'şivşirmek', 'tahra', 'taka', 'takda delen', 'tamaş etmek', 'tandır', 'tangazak', 'tangrı canını ala', 'tantana', 'tapandan gelik', 'tarana firii', 'tarkan tarkan yarılmak', 'tarpadan', 'taşgala', 'taşgalıya almak', 'tavatır', 'tavlak', 'teccel', 'teh', 'teleme', 'teltik', 'tengi terezi', 'terbiye tarlasından geçmemiş', 'tesbi gılii', 'tesbi', 'teserleme', 'teşt', 'tetiri', 'tevek', 'tevir', 'tılısımı kırılmak', 'tıngırık', 'tınsırık', 'tırıp', 'tırpan', 'tinkmek', 'tintirik', 'tirşik', 'tiyara', 'tokaç', 'tomatis mancası', 'tomus', 'toscu', 'töde', 'tumdurmak', 'tusbaa baarsılığı', 'tusbaa', 'tusmuk', 'tuulu, tülü', 'tük', 'ufra', 'ulama', 'umsuluk', 'unnuk', 'uruk guşu', 'uruplaa', 'uunmak', 'uyluk', 'üçgül', 'üfelemeç', 'üfürümüssün mere', 'ütmek', 'varan gelen', 'varınşık', 'velvele', 'vıcık', 'vırtgel', 'vıttırı vızzık', 'vıykırmak', 'vızzık', 'yaalık', 'yaba', 'yalbırdak', 'yalpalamak', 'yamıktırmak', 'yanaz', 'yannık', 'yazlak', 'yemşen', 'yetik', 'yiyen', 'yörebi aamak', 'yörep', 'yuva eee!', 'yüklük', 'yülemek', 'zavara', 'zavırlamak', 'zehmeri', 'zerzambıl', 'zıbarmak', 'zıkımın dibi', 'zırnık', 'zıypınmak', 'zibidi', 'zibil, zibillik', 'zillemek', 'zincar', 'ziv ziv gezmek', 'ziyakıl getmek', 'zobu', 'zomp', 'zomzalak', 'zopur', 'zopzopu', 'zorlu olmuş', 'zorsunmak', 'zoruna getmek', 'zumzuk', 'zupban', 'züpbe'];

let Tkelimeler = ["O anda yapılan bir iş veya davranışın aşırıya kaçtığı durumlarda kullanılır.", "Aşırıya kaçan durumlarda “hayret ünlemi” olarak kullanılır.","(ağız) İneğin yavruladıktan sonraki ilk sütü.",
"ağıl","yeni","domuz", "ölesice", "kavun", "bunalmak","alabak kuşu", "Bir kuş türü.", "Allah bilir","dua etme", "Allah temiz,açık bahtlar versin.", "emanet", "Yaşı ilerlemiş, gözü açılmış", "Daha çok taşıtların geri geri gitmesi demektir.", "Tertemiz", "tüketim malzemelerinin kullanılmaz hale gelmesi veya getirilmesi demektir.", "Aşılanmış", "Ağıllardan geçen yol, yolak", "Aşağı", "(avare) Boş gezen, işi olmayan anlamındadır.","Biber, patlıcan vs. ekilen yere denir", "Aşırı nemli hava", "soğuk","Bu zamanda kesilen ağaç daha uzun süre dayanır.", "Bir tür ot","Tarlaya götürülen yiyecek","göğüs kafesi","bukelamun", "Pirecik ", "Başı eksik anlamında kullanılır. Tam dolu olmayan.", "Bayramda giyilmek için alınan giyecekler.", "Küçük yufka ekmek, gözleme","Çıkrıklarda eğrilecek ipin dolandığı yer.", "testere","Geçen yıl", "Yaramaz çocuk", "hala", "Tohum", "Plastik Kavanoz","Yağmurun birden başlayıp durması.", "Birinin hoşuna gitmesini istediği davranışlarda bulunmak.", "Az sonra", "Güveç", "Yayıktaki ayranı karıştırmaya yarayan çubuk.", "Az önce", "Sürahi.", "Ekin tarlaları arasında ekilip sürülmemiş otu bol olan yer.", "Bir delikten geçirmek.", "Öküzlere tarla sürülürken takılan boyunluk","Kül rengi",
"örümcek", "Bugün", "Bir çeşit şapka", "Kapşon", "Erkekler için kullanılan samimi ifade.", "Bu kadar, Bu kadarcık.", "Bu sefer", "Dumandan, isten bunalmak.", "İçine girilemeyen çalılık", "Bir çeşit hayvanlara iğne batıran sinek.","Küçük havuz (kısıtlı imkanlarla yapılan havuzcuk)", "Mutfak, banyo gibi yerlerin atık su gideri.","Ses, herhangi bir şeyin etrafını etkileyerek ses yapması.","Manda.","Çekişmek. Tartışmak, gürültü etmek, etrafı rahatsız etmek anlamında | Laf kalabalığı","Çok konuşan, tartışan kişi (kadınlar için kullanılır)","farenin büyüğü","Bir kumaş türü","Üzerinde hiçbir şey olmayan, kel.","piliç","Gereksizce bağırmak.","biçimsiz","elektrik","domuz yavrusu","Madeni para","Bozulmuş yumurta","Kavgacı, oyun bozan","Yan çizmek, oyun bozanlık yapmak.","Kavga çıkarmak, anlaşmazlık çıkarmak","ağustos böceği","Tırnak, diken çiziği","Tamamen","maki türü","Ciğerinden hastalanasın, ölümcül hastalığa yakalanasın","Küçük, yumurtlamayan tavuk","Sigara","Suyun yüzeyinde bulunan kurumuş yaprak, gazel.","Hartlap ağacının meyvesi.","Genellikle tarlaların kullanılmayan yerindeki toplanan taş yığını.","1.Gelişmemiş 2. Karışık durum.","1.Tarlada ürünlerin arasını süren tarım aleti 2. Büyük kazma.","Evin dışında oturmak için kullanılan “kamelya”","Topuğu bükülmüş ayakkabı.","Kuş avlamak için kullanılan lastiklerde (sapan) içine taş konulan deri bölüm.","Bir böcek türü","Herhangi bir şeyin ani veya hızlı ses çıkarması","Su içmek için su kaynağının önüne yapılmış küçük havuzcuk.","Oğlağın büyüğü","Ağız kavgası.","Pirincin tarladaki hali","parça, yarım, diğer yarısı","Bacaklarından ayırmak.","Bulaşık",
"Traktörde römorkun üzerine tahtalarla ilave yapılmış şekli.","Fide","Suyun döndüğü yer. Kıvrımlı akıntı.","Tamamen",
"Yün eğirmek için yapılmış; kasnak, bekere ve ayaktan oluşan mekanizma.","Küçük dal.","parça","Menengiç ağacı","Herhangi bir şeyin etkisiyle çıkan küçük ses.","Pamuğun çiğ yağdıktan sonra kabuğuyla beraber toplanması.","Küçük parça","Banyo yapmak.","Kuş","Küçük parça (saydam taş için de kullanılır)","Çiğ gibi, çiğe yakın.","Ağacın kollarının ilk ayrıldığı yer","Büyük tahta kaşık.","Keçi kılından dokunan yaygı olarak kullanılan düz desensiz dokuma.","Davulun tokmağı","Cimri (tenezzül etmek)","Herhangi bir şeyin çoğalması için saklanan numune, örnek","Toprağın nemi.","Ses, herhangi bir şeyin hareket ettiğini belirten ses.","Aşırı gerilmek.","sürekli","Traktörle pulluk, çapa, gaster gibi tarım aletlerinin yukardan da bağlantısını sağlayan alet","Genellikle tarhanayı pişirirken karıştırmak için kullanılan araç.","Tekme","toplamak",
"Ertesi gün.",
"sisileli, dolambaçlı durumlar için kullanılan bir söz.",
"girmek",
"Az nemli.",
"Bir olayın ayrıntısını öğrenmeye çalışmak",
"Saçın traş makinasıyla sıfır numaraya kesilmesi",
    "Keyif",
"Meyili çok olan yer",
"Anahtar","Tepe, uç nokta.",
"Herhangi bir şeyin tam oturması.",
"Ekin sapını patosa vermede veya bir yere taşımada kullanılan alet.","Dokuz taş.",
"takla",
"Deyyusun beslediği","Rüzgar eserken, rüzgarın etki etmediği, ulaşamadığı yer.",
"Az pişmiş bazlama (gözlemenin) eriştenin ekşili mercimek veya pirinçle pişirildiği bir tür yemek türü",
"Çirkin sarışın.","Arka arkaya yapılan hatadan sonra söylenen bir ünlemdir.",
"Meşe",
"El ve ayak yıkamak için kullanılan araç. Seyyar lavabo","manasız",
"(iletmek) ulaştırmak",
"Genellikle çardak ve hayma yaparken kullanılan, direkle tavanı oluşturan ağacı bir birine bağlayan ağaç.","Her halde anlamındadır. Yanlış bilinen bir durum sonrası da söylenir.",
"Yengeç",
"Ekin biçerken parmaklara takılan elçek.","Keçinin yeni doğmuş yavrusu.",
"Bilye oynarken, dikilen madeni para.",
"Hayvan yavrusu.","Bekleme s    üresini uzatmak için tereyağın eritilmiş ve tuzlanmış hali.",
"(essah mı?) Sahi mi? Gerçekten mi?",
"Aşikar, apaçık, Herkes tarafından fark edilebilen","Evin giriş kısmı",
"Evlenmeye aday, evlenmek isteyen kişi.",
"Acele etmek","Yufka ekmeği döndürmek için kullanılan ağaçtan yapılan yassı araç",
"Kuş avlarken, kuştan gizlenmek için yapılan çalılardan yapılan evcik.",
"Zaman geçirmek, ayak sürümek.","tuzak",
"(fakih) Hoca.",
"(hedik) Kaynamış mısır, buğday tanesi.","Sendelemek",
"Düzensiz bir şekilde atmak.",
"küçük yağmurlama","topaç",
"İlaçlamada kullanılan motorsuz, elle çalışan zirai mücadele aracı.",
"paramparça","Anız",
"olgunlaşmamış",
"eski aydınlatma aracı","Küçük bir kuş türü.",
"mezarlık",
"Hoyratça hareket eden genç.","Tasasını, kaygısını, kederini almak, üstlenmek.",
"(kadeh) Kulplu bardak.",
"Anormal davranışlarda bulunanlar için söylenir","Orağın küçüğü.",
"Güvercin",
"Sincap","Ağır hareket eden. (Kanı ağır)",
"Odunun kesmenin etkisiyle oluşan parçası.",
"Kamış","Büyük çukur.",
"kaban",
"Fenni olmayan, uzun, el yapımı kovan.","kargı",
"(karaçalı) Dikenleri uzun ve çok olan bir maki türü.",
"(karartı) Tam seçilemeyen, ne olduğu anlaşılamayan görüntü.","karanlık olmak",
"Kızarak suçlayıcı sözler söylemek.",
"Hoş kokulu bir ot türü."," İnadına yapmak.",
"Kar pekmez karışımı yiyecek.",
"Avlunun tahtadan yapılmış kapısı.","Arpanın yeşil, başak çıkarmamış hali.",
"Modern ilaçlama makinesi.",
"Keçi, koyun gibi küçükbaş hayvanlar için yapılan korunak","Koyun ve keçi konulan ağaçlarla çevrilen, üzeri açık veya kapalı yer.",
"ayran (Torba gatığının özenerek ayran haline getirilmesi.)",
"Patlamış mısır","Kavrulmuş buğday yada mısır öğütülerek yapılan yiyecek.",
"Ot türü",
"Kurumuş yaprak.",
"Ot türü",
"Buğdayı harmanda öğütmek için kullanılan altında sivri taşların çakılı olduğu, öküzlerin çektiği bir araç.",
"Bir olayı yapmak için istekli bir şekilde beklemek",
"Tohum.",
"kıçı kırık, beğenilmeyen",
"Küçük domates.",
"Sarışın birinin güneşin etkisiyle daha da sarışınlaşması.",
"Kıral Ağacı.(zomzalak)",
"Kıran gele, gelsin. Kökü kurusun!",
"Niyetinin kötü olduğunu belli etmek",
"Küçük parçalara ayırmak.",
"Eski bir kumaş çeşidi",
"Koyun, keçi gibi küçükbaş hayvanları traş etmek için kullanılan alet",
"Gagası uzun bir kuş türü.",
"Küçük soğan tohumu.",
"Herhangi bir şeyin sıkışması.",
"Dokuma olmayan hazır, naylon karışımı(naylondan) olan torba.",
"Burmalı (bilezik)",
"Herhangi bir şeyin çok olduğunu belirtmek için kullanılan bir söz.",
"Maddesi ağaç olan her maddeden batıcı, delici küçük parça.",
"Küçük kum veya toprak parçası.",
"kıpkırmızı",
"Ot türü",
"ısınmak",
"Çekinmek.",
"ukala",
"Hepsi, tamamı.",
"boş, kovuk",
"Araba anahtarı.",
"Dedi kodu etmek.",
"Sürülmüş tarladaki kesekleri ezmek ufalamak için kullanılan tarım aleti.",
"Pamuğun yapraksız çubuğu.",
"Mantar",
"Buğdayların göceklemesi(çoğalması) için atılan gübre.",
"şişman",
"Güzel, alımlı.",
"Göğüs kısmı sarı olan küçük bir kuş türü",
"deri",
"(göyünmek) Ateş veya ısının etkisiyle, yanmaya yaklaşmak. (Neredeyse yanmak.)",
"olgunlaşmamış",
"Geri geri gitmek.",
"şişmek",
"İki omuz arası, sırt.",
"kominist",
"gebe",
"Civciv çıkarma zamanı gelen, çıkarmak isteyen tavuk.",
"Ahlat türü.",
"gayışkanat",
"Küçük leğen.",
"kovan",
"Can vermek (guyru titiretmek)",
"Bilye",
"Ağaç yayık.",
"Ne çabuk bre ulan",
"Ne çabuk.",
"Yavrulamamış keçi.",
"Gereğini yapmak, dersini vermek",
"Kalbur",
"Yeşil karpuz türü.",
"Aşılı mersin.(maki türü)",
"Tereyağı saklanan kap.",
"Bir parçanın tamamıyla istenilen yere düşmesi.",
"Kuş tutmak için yapılan kapan.",
"Ketenden yapılmış büyük çuval.",
"biçimsiz",
"Kocayemiş",
"Hasta ziyaret etmek",
"Küçük çalı, yaprak karışımı kırıntı.",
"Genellikle güneşten korunmak için dört direk üzerine yapılır, üzeri ağaç dallarıyla kapatılır.",
"Geveze, afacan.",
"yabani sarmaşık",
"İki cebi olan, dokunmuş, eskiden eşya taşımak, gübre atmak için kullanılan bir eşya.",
"Küçük taş parçası.",
"Satır, su kabı.",
"Emaneten duran, sallanan, her an yıkılabilir.",
"Sallanmak.",
"Bey",
"üzüm döküntüsü",
"Salıncak",
"Eskiden, kağıtlara yazılan kelimeleri bulmayla ilgili bir oyun.",
"Hayvanların tekmesi.",
"Eklem yerlerinin kayması, zedelenmesi.",
"Epeyce.",
"Pamuğun kabuğuyla toplanmış hali.",
"Acur",
"Hevesi gitmek, isteğinin bitmesi, dediğinin olması.",
"Büyük sopa.",
"Omuzlarına almak",
"Tohum",
"Sırtına almak",
"ev halkı",
"Susamın sapıyla beraber kurutulması için belinden bağlanmış ve bir birine yaslanmış koni hali.",
"Diklenmek",
"Hoşuna gitmek.",
"Olgunlaşmamış incir.",
"Kanı soğuk.",
"Tohumu su ile karıştırarak, tohumun nemlenmesini sağlamak.",
"Ses çıkararak, kahve veya çay içmek.",
"İşe yaramaz.",
"Saptan yapılan korunak.",
"Tehlikeden haberdar olmak, bir yere gitmek istememek.",
"(fuzuli) Gereksiz yapılan harcama",
"Yeltenmek",
"Sus",
"Sallanmak, bir binanın sallanması",
"İbrik",
"Sürgün, filiz.",
"eşkıya",
"Şafak sökmeden",
"Irzı kırık (Irkı bozuk, soyu belirsiz) çocuğu.",
"Sipariş",
"İbibik kuşu.",
"Huylanmak, şüphelenmek, kötü bir durum sezmek.",
"yaramaz",
"Kertenkele benzeri bir sürüngen.",
"Başı dibi olmayan, gereksiz, kayda değer bir şey olmayan.",
"domuz",
"çok",
"Yazmanın kakül görünecek şekilde bağlanması.",
"kazma",
"Tadının ekşi veya acıya yakın olması.",
"Bayanlar için kullanılan samimi ifade.",
"kertenkele",
"dik duran bir şeyin yıkılması",
"Ters davranmak.",
"kertenkele",
"Vurmak için harekete geçmek",
"meşe çeşidi",
"Malzeme taşımak için iki ağaç üzerine üç tarafı kapalı araç.",
"tas",
"fırlatmak",
"Yünden ip yapar",
"Sabunun en küçük hali",
"iliklerini sökmek",
"Sarışın, kirli sarışın.",
"Ucu sivri sopa.",
"Yaprakları yemek yapmada kullanılan bitki.",
"Sulama borularının en ucuna takılan tapa.",
"Demir aletlerinin yapıldığı yer.",
"yarasa",
"iskemle",
"Eskiden gömlek yerine geçen bir giyecek",
"Halı ve kilim dokumak için kurulan tezgahta ipleri tutan kalın sopa.",
"bkz.horum",
"Susamları sapıyla beraber kurutmak için bağlanmış hali.",
"susam",
"her gün",
"Kuş türü",
"burçak",
"demir parçası",
"römork",
"Nemlenme",
"1.Bulgur veya pirinçten yapılan bir tür yemek. (ölgünürek lepe) 2.Nohutun ıslatılıp kurutulduktan sonra dövülmesinden elde edilen yemek.",
"Düğün yemeği.",
"Elektriksiz çalışan aydınlatma aracı.",
"Uzun ağaç",
"Rezil olmak",
"şamatacı",
"Domates salatası.",
"Adı geçmez olmak, adı anılmamak.",
"Ağır ağır, kaygısızca yürümek.",
"Sohbet etmek.",
"al anlamına gelir",
"patlamış mısır",
"Mısır püskülü.",
"Mısır koçanı",
"mısır",
"Labıtın çubuğu",
"çivi",
"cimri",
"Midenin ekşimesi.",
"gömlek",
"Eskimiş, parçalanmış",
"küçük sinek",
"mersin",
"naylon",
"Kesilmiş kullanılmak üzere uzun ve kalın ağaç.",
"almayı istemek",
"Ne zaman",
"Sapı olmayan bıçak.",
"Ne tutuyorsun, ne yapıyorsun?",
"Anlatılamayan ve kafasına yatmayan bir davranış, söz sonrası söylenir.",
"ne çeşit",
"Ne imiş, küçümsemek için kullanılır.",
"Ne yapmalı, ne gerek var, boşver anlamlarında kullanılır.",
"Nişe yemeği",
"Buğdayın bekletilerek suyunun kurutulmasıyla elde edilen özü",
"Başkaları ne söyler",
"(ocaktan ırak) Ailelerden, evlerden uzak olsun",
"davetiye",
"belini ağrıtmak",
"Güzelim, ne güzel.",
"Omzuna alıp getirecek kadar ağır olmayan kesilmiş ağaç.",
"Ondan sonra.",
"Oynamıyorum, oyundan çıktım, mola",
"Az pişmiş lepe.",
"Ölünün körü, beddua.",
"Çok zayıf, cılız.",
"Hayvanı uzun bağlamak.",
"Örgü hayvan bağlamaya yarayan ip.",
"Örülmüş ip.",
"Evin önündeki düz alan.",
"İhtiyaç malzemeleri.",
"İshal olmak.",
"Atların semerini vücuduna bağlayan kuşak.",
"pelit, palamut, meşegiller tohumu",
"gelincik",
"Kaban",
"bacaklarını açmak",
"Bacak arası.",
"Hayvan sesi.",
"Bir tür yabani siyah üzüm.",
"havlu",
"yeşil meşe kategorisinden bir ağaç türü.",
"Giysi, giyecek.",
"Yuvasından çıkmak.",
"Saklambaç oyunu.",
"saklanmak.",
"1.yumurta 2. bacak arası 3. Ardıç ağacının meyvesi",
"kümes",
"pantolon",
"Herhangi bir şeyin nemden dolayı kokması, pörsümek.",
"Bir delikten geçirmek, boşandırmak",
"Selin yolu bozmaması için, yolun altından geçen beton boru",
"Çamın kurumuş yaprağı.",
"Tohumun ucu.",
"kedi",
"sapsarı",
"Öküzlerle tarla sürmede kullanılan ilkel pulluk.",
"Saç ayağı. Üç ayağı olan, üzerinde genellikle yemek pişirilir",
"dengesiz kişi",
"kene",
"kabuklu tohum",
"Boyunduruk deliğinden geçen çubuk.",
"(santrifüj) Sulama aracı",
"zaturre, ölümcül hastalık",
"Büyük kalbur.",
"Günlük kullanım için dokunmuş kilim",
"geçip gitmek",
"Esamesiz, yerli, yersiz konuşan kimse.",
"Eksik, tam dolu olmayan.",
"Uzak yer, öte",
"Dikkat etmeden, gereksiz, hoyratça, olur olmaz konuşan.",
"Kamıştan örülen, incir, üzüm taşımada kullanılan araç.",
"Düğünlerde genellikle 5, 6 kişiyle oynanan bir oyun çeşidi",
"Sehlikliği ve dağınıklığı huy edinmiş kişi.",
"sıcak, bunaltıcı hava",
"gülümsemek",
"sürekli gülmek",
"bukalemun",
"kaygan, aşırı kaygan",
"demir kazık",
"Dolu, ağzına kadar dolu",
"tokat, elle vurma",
"Yağmurun yavaş yavaş yağması",
"Alım satımlarda arabulucuya denir.",
"Hedef küçülterek, avına yaklaşmak.",
"Düğünlerde ateş üzerinden atlama esasına dayanan bir oyun çeşidi",
"ayıklamak",
"Semiz otundan yapılan yoğurtlu yiyecek",
"semiz otu",
"dürüm",
"sumak",
"Ölünün üzerinden çıkan giysi.",
"Küçük bebek, kundaktaki bebek.",
"yaslanmak",
"Kiraz",
"salyangoz",
"Yapılarda karşıdan karşıya uzatılan ağaç.",
"İşaret parmağı ile baş parmağın uçları arasındaki uzaklık",
"sürülmüş tarla",
"Küçük ağaç direk.",
"çatının uç noktası",
"süs kabağının oyularak, su kabı olarak kullanılması",
"tokat, elle vurma (sille)",
"Ters, eğri, düzgün olmayan",
"ters ters konuşmak",
"yük",
"yulaf",
"pamuk kabuğu",
"8 kg. ağılığında tahıl alabilen ağırlık ölçüsü. Kilenin(iki tenekenin) Â¼ ü",
"tatlı",
"kışkırtmak",
"Çalı kesmek için kullanılan kesme aleti",
"Çardak",
"Ağaçları delerek içindeki böcekleri yiyen bir kuş türü.",
"seyretmek",
"Üzerinde çörek pişirilen yassı taş.",
"kuru, kurumuş",
"Allah canını alsın",
"Boş laf.",
"öküz gibi Genellikle yorgun olmayıp da, yorgunmuş gibi davranan veya yersizce uzanan kimseye söylenir.",
"Tarhananın tam kurumamış, yarı kurumuş hali.",
"Toprağın kuruyarak büyük büyükyarılması.",
"aniden",
"Alaya almak, dalga geçmek.",
"Alaya almak",
"güzel",
"ceviz",
"sakar",
"Güzel olmuş anlamında kullanılan bir söz.",
"Keçi, koyun, inek gibi hayvanların çiğ sütünden incir sütüyle mayalanan yiyecek.",
"bir adı var söylemesi zor ismi olan bir kişi.",
"düzenli, ucu ucuna",
"Toplum kurallarına ve adetlerine uymayan kimseye denir. (Uyumsuz, ukala kimselere)",
"Tesbi ağacının tohumu.",
"Bir maki türü.",
"Örnek vermek",
"leğen",
"maki türü tohumu sumak",
"üzüm bağı",
"çeşit",
"İştahının kaçması, isteğinin gitmesi.",
"Ortası delik, metal altlık.",
"hapşırmak",
"Çok var anlamında kullanılır.",
"Tahradan ucu daha uzun kesme aleti.",
"sekmek",
"parmak sopası, fiske",
"Yabani pancar çorbası.",
"uçak",
"Çamaşır yıkarken çamaşırlara vurmak için kullanılan biçimli sopa.",
"domates salatası",
"Temmuz",
"Değirmen işleten, değirmenci.",
"Fidanların çevresinin çalılarla örülmesi.",
"Bir kişiyi suya batırmak",
"Yabani olarak yetişen, çiçekleri olan bir ot.",
"kaplumbağa",
"küçük odun kökü parçası",
"Saçı karışık, daha çok sevgi maksadıyla küçük çocuklar için kullanılır",
"Soğan tohumluğu.",
"Hamura kıvam veren un.",
"Bezden dokunmuş yolluk",
"Bunalmak, sıkıntıya düşmek.",
"Un öğütmek için hazırlanmış buğday.",
"arı kuşu",
"Çeyrek şinik",
"katıla katıla gülmek, aralıksız gülmek",
"bacak, bud",
"yonca",
"Yufka ekmek ufağı, yağ, şeker karışımı yemek.",
"Meğerse hafifmişsin, iyi değilmişsin.",
"yenmek",
"Dokuma tezgahlarındaki kalınca sopa.",
"varınca",
"gürültü, ortalığı karıştırmak",
"Bir kuş çeşidi.",
"Dokurcun oyununda her oynamada taş alma durumu",
"Hiç önemi yok",
"bağırmak",
"izmarit",
"eşarp",
"Saman atmakta kullanılan tahta kürek",
"Çıplak",
"sendelemek",
"çökertmek",
"Şap, şapşal, ters, ters hareket eden kimse.",
"yayık",
"Yazın serinlemek için gidilen geçici ev.",
"alıç ağacına benzer yabani yemişleri olan bir ağaç.",
"Olgunlaşmış, yenecek hale gelmiş meyve veya sebzeye için kullanılır",
"yeğen",
"Yokuşa başlamak.",
"yokuş",
"Aşırıya kaçan davranışlarda söylenir.",
"Yatak konulan yüksek yer.",
"keskinleştirmek",
"Değişik tahıllardan öğütülmüş hayvan yemi.",
"Kızmak, payını vermek, paylamak.",
"Karakış",
"Büyük yer altı mağarası.",
"ölmek zahar herhalde, galiba",
"zakkumun (cehennem içeceğinin koyu yeri) dibi",
"zerre",
"Kaymak, isteyerek kaymak",
"Boşu boşuna gezen.",
"hayvan gübresi, gübreliği",
"filizlemek",
"Dikenlik",
"Boşu boşuna gezmek.",
"Aşırı yorgunluktan (yarı baygın şekilde) uyuyakalmak.",
"işe yaramaz",
"Kullanılmak üzere kesilmiş düzgün, biçimli kalın ağaç.",
"ağaç türü",
"Aniden gelip geçen yağmur.",
"Gaco, hoyratça hareket eden genç",
"Güzel olmuş",
"Zor zannetmek, erinmek.",
"alınmak",
"yumruk",
"Kuş türü",
"Geveze, soytarı",
];
function aldimkabulettim777(){
    let tr = document.getElementById("text-area").value;
    let trlower = tr.toLowerCase();
    let a
    for (var i = 0; i <= Tkelimeler.length; i++){
        a = trlower.indexOf(kelimeler[i]);
        if (a != -1){
            document.getElementById("txt-answer").innerHTML = Tkelimeler[i];
            break;
        }
        else {
            document.getElementById("txt-answer").innerHTML = "Girdiğiniz kelime veri tabanında yok veya teker teker girerek tekrar deneyiniz.";
        }
    }
}

document.getElementById("eee").innerHTML = kelimeler.length + 1;

